// auth schema
export {
  authSchema,
  users,
  wallets,
  userRoles,
  sessions,
  adminAuditLog,
  userStatusValues,
  walletSourceValues,
  roleNameValues,
  sessionAppValues,
} from './schema/auth';
export type {
  UserStatus,
  WalletSource,
  RoleName,
  SessionApp,
  User,
  NewUser,
  Wallet,
  NewWallet,
  UserRole,
  NewUserRole,
  Session,
  NewSession,
  AdminAuditLog,
  NewAdminAuditLog,
} from './schema/auth';

// app schema
export {
  appSchema,
  betTemplates,
  bets,
  betParticipants,
  betRules,
  betArbiters,
  betEvidence,
  betEvents,
  betAuditLog,
  betShareLinks,
  betStatusValues,
  betTypeValues,
  resolveTypeValues,
  arbiterTypeValues,
  arbiterAssignmentStatusValues,
  participantRoleValues,
  betEventTypeValues,
  actorTypeValues,
  disputes,
  disputeStatusValues,
  autoResolveAttempts,
  autoResolveStatusValues,
  settlements,
  settlementKindValues,
  payouts,
  payoutStatusValues,
  payoutAttempts,
  payoutAttemptStatusValues,
  userReputation,
  reputationTierValues,
  reputationRecomputeQueue,
  reputationRefreshReasonValues,
  riskScores,
  riskAlerts,
  riskEdges,
  riskRecomputeQueue,
  riskBandValues,
  riskAlertTypeValues,
  riskAlertStatusValues,
  riskSubjectTypeValues,
  riskRefreshReasonValues,
  cronRuns,
  opsAlerts,
  cronRunStatusValues,
  opsAlertTypeValues,
  opsSeverityValues,
  opsAlertStatusValues,
} from './schema/app';
export type {
  BetStatus,
  BetType,
  ResolveType,
  ArbiterType,
  ArbiterAssignmentStatus,
  ParticipantRole,
  BetEventType,
  ActorType,
  BetTemplate,
  NewBetTemplate,
  Bet,
  NewBet,
  BetParticipant,
  NewBetParticipant,
  BetRule,
  NewBetRule,
  BetArbiter,
  NewBetArbiter,
  BetEvidence,
  NewBetEvidence,
  BetEvent,
  NewBetEvent,
  BetAuditLog,
  NewBetAuditLog,
  BetShareLink,
  NewBetShareLink,
  Dispute,
  NewDispute,
  DisputeStatus,
  AutoResolveAttempt,
  NewAutoResolveAttempt,
  AutoResolveStatus,
  Settlement,
  NewSettlement,
  SettlementKind,
  Payout,
  NewPayout,
  PayoutStatus,
  PayoutAttempt,
  NewPayoutAttempt,
  PayoutAttemptStatus,
  ReputationTier,
  ReputationRefreshReason,
  UserReputation,
  NewUserReputation,
  ReputationRecomputeQueueRow,
  NewReputationRecomputeQueueRow,
  RiskBand,
  RiskAlertType,
  RiskAlertStatus,
  RiskSubjectType,
  RiskRefreshReason,
  RiskScore,
  NewRiskScore,
  RiskAlert,
  NewRiskAlert,
  RiskEdge,
  NewRiskEdge,
  RiskRecomputeQueueRow,
  NewRiskRecomputeQueueRow,
  CronRunStatus,
  OpsAlertType,
  OpsSeverity,
  OpsAlertStatus,
  CronRun,
  NewCronRun,
  OpsAlert,
  NewOpsAlert,
} from './schema/app';

// financial schema
export {
  financialSchema,
  ledgerEntries,
  balances,
  freezeState,
  reconciliationRuns,
  deposits,
  orphanDeposits,
  accountTypeValues,
  directionValues,
  ledgerReasonValues,
  freezeComponentValues,
  reconciliationStatusValues,
  depositStatusValues,
  depositRejectionReasonValues,
  orphanDepositStatusValues,
} from './schema/financial';
export type {
  AccountType,
  Direction,
  LedgerReason,
  FreezeComponent,
  ReconciliationStatus,
  LedgerEntry,
  NewLedgerEntry,
  Balance,
  NewBalance,
  FreezeStateRow,
  ReconciliationRun,
  Deposit,
  NewDeposit,
  OrphanDeposit,
  NewOrphanDeposit,
  DepositStatus,
  DepositRejectionReason,
  OrphanDepositStatus,
} from './schema/financial';

// client
export { createDb } from './client';
export type { Database, DbHandle } from './client';
